parameters:
  - name: registry
    type: string
  - name: organization
    type: string
  - name: feed
    type: string
  - name: package
    type: string

steps:
  - template: /.devops/templates/download-artifact.yml@self
    parameters:
      displayName: Download ORAS
      organization: ${{ parameters.organization }}
      feed: ${{ parameters.feed }}
      package: ${{ parameters.package }}
      version: 1.1.0
      downloadPath: $(Pipeline.Workspace)/oras-download

  - template: /.devops/templates/install-artifacts.yml@self
    parameters:
      displayName: Install ORAS
      binaryName: oras

  - task: AzureCLI@2
    displayName: Annotate previous amd64 as EOL
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      scriptLocation: "scriptPath"
      scriptPath: $(Build.SourcesDirectory)/scripts/image-annotation.sh
      arguments: >
        --registry ${{ parameters.registry }}
        --manifest $(imageDigestAmd64)

  - task: AzureCLI@2
    displayName: Annotate previous arm64 as EOL
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      scriptLocation: "scriptPath"
      scriptPath: $(Build.SourcesDirectory)/scripts/image-annotation.sh
      arguments: >
        --registry ${{ parameters.registry }}
        --manifest $(imageDigestArm64)