parameters:
  - name: registry
    type: string
  - name: organization
    type: string
  - name: feed
    type: string

steps:
  - template: /.devops/templates/download-artifact.yml@self
    parameters:
      organization: ${{ parameters.organization }}
      feed: ${{ parameters.feed }}
      package: oras-linux-x64
      version: $(ORAS_VERSION)

  - task: AzureCLI@2
    displayName: Annotate previous amd64 as EOL
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      scriptLocation: "scriptPath"
      scriptPath: $(Build.SourcesDirectory)/scripts/image-annotation.sh
      arguments: >
        --registry ${{ parameters.registry }}
        --manifest $(imageDigestAmd64)

  - task: AzureCLI@2
    displayName: Annotate previous arm64 as EOL
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      scriptLocation: "scriptPath"
      scriptPath: $(Build.SourcesDirectory)/scripts/image-annotation.sh
      arguments: >
        --registry ${{ parameters.registry }}
        --manifest $(imageDigestArm64)