parameters:
  - name: registry
    type: string

steps:
  - bash: |
      REGISTRIES=${{ parameters.registry }}:$(version)-$(distro)
      if [[ "$(distro)" == "azurelinux" ]]; then
        REGISTRIES+=",${{ parameters.registry }}:$(version)-mariner"
      fi
      echo "##vso[task.setvariable variable=REGISTRIES]$REGISTRIES"
    displayName: Set REGISTRIES variable

  - bash: |
      BUILD_ARGS="--platform linux/amd64,linux/arm64 --build-arg package=$(package)"
      if [[ "$(distro)" == "distroless" ]]; then
        BUILD_ARGS="$BUILD_ARGS --build-arg INSTALLER_IMAGE=$(installer_image) --build-arg INSTALLER_TAG=$(installer_tag) --build-arg BASE_IMAGE=$(base_image) --build-arg BASE_TAG=$(base_tag)"
      else
        BUILD_ARGS="$BUILD_ARGS --build-arg IMAGE=$(image) --build-arg TAG=$(tag)"
      fi
      echo "##vso[task.setvariable variable=BUILD_ARGS]$BUILD_ARGS"
    displayName: Set BUILD_ARGS variable

  - task: 1ES.BuildContainerImage@1
    retryCountOnTaskFailure: 2
    inputs:
      image: ${{ parameters.registry }}:$(version)-$(distro)
      context: $(Build.SourcesDirectory)
      dockerfile: $(Build.SourcesDirectory)/docker/$(distro)/Dockerfile.$(package)-jdk
      enableNetwork: true
      useBuildKit: true
      buildArguments: $(BUILD_ARGS)
    displayName: Build image

  - task: 1ES.PushContainerImage@1
    inputs:
      image: ${{ parameters.registry }}:$(version)-$(distro)
      remoteImage: $(REGISTRIES)
    displayName: Publish image