parameters:
  - name: acr_registry
    type: string
  - name: version
    type: string
  - name: distro
    type: string

steps:

  - task: AzureCLI@2
    displayName: Azure CLI ACR login
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az acr login -n junipercontainerregistry
        az acr login -n "$(ACR_NAME)"

  - bash: |
      PRIMARY_IMAGE="${{ parameters.acr_registry }}:${{ parameters.version }}-${{ parameters.distro }}"
      REMOTE_IMAGES="$PRIMARY_IMAGE"
      if [[ "${{ parameters.distro }}" == "azurelinux" ]]; then
        REMOTE_IMAGES+=",${{ parameters.acr_registry }}:${{ parameters.version }}-mariner"
      fi
      echo "##vso[task.setvariable variable=PRIMARY_IMAGE]$PRIMARY_IMAGE"
      echo "##vso[task.setvariable variable=REMOTE_IMAGES]$REMOTE_IMAGES"
    displayName: Set image variables

  

  - task: 1ES.BuildContainerImage@1
    displayName: 1ES Build container
    inputs:
      image: $(PRIMARY_IMAGE)
      dockerfile: docker/${{ parameters.distro }}/Dockerfile.msopenjdk-${{ parameters.version }}-jdk
      enableNetwork: true
      useBuildKit: true
      context: docker/${{ parameters.distro }}
      ${{ if eq(parameters.distro, 'distroless') }}:
        buildArguments: >
          --platform linux/amd64,linux/arm64
          --build-arg INSTALLER_IMAGE=$(installer_image)
          --build-arg INSTALLER_TAG=$(installer_tag)
          --build-arg BASE_IMAGE=$(base_image)
          --build-arg BASE_TAG=$(base_tag)
          --build-arg package=$(package)
      ${{ else }}:
        buildArguments: >
          --platform linux/amd64,linux/arm64
          --build-arg IMAGE=$(image)
          --build-arg TAG=$(tag)
          --build-arg package=$(package)

  - task: 1ES.PushContainerImage@1
    displayName: 1ES Push container
    inputs:
      image: $(PRIMARY_IMAGE)
      remoteImage: $(REMOTE_IMAGES)