parameters:
  - name: organization
    type: string
  - name: feed
    type: string
  - name: package
    type: string
  - name: version
    type: string

steps:
  - task: AzureCLI@2
    displayName: Download ${{ parameters.package }} ${{ parameters.version }}
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az artifacts universal download \
          --organization "${{ parameters.organization }}" \
          --feed "${{ parameters.feed }}" \
          --name "${{ parameters.package }}" \
          --version "${{ parameters.version }}" \
          --path "${{ parameters.package }}"

        echo "[DEBUG] Listing directory for debug"
        ls -la ./${{ parameters.package }}
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

  - bash: |
      archive="$(find "${{ parameters.package }}" -maxdepth 1 -type f -name '*.tar.gz' -print -quit)"
      echo "##vso[task.setvariable variable=ARCHIVE]$archive"
    displayName: Find ${{ parameters.package }}

  - bash: tar xf "$(ARCHIVE)" -C "$(Pipeline.Workspace)"
    displayName: Extract ${{ parameters.package }}
