parameters:
  - name: organization
    type: string
  - name: feed
    type: string
  - name: package
    type: string
  - name: version
    type: string

steps:
  - task: AzureCLI@2
    displayName: Download ${{ parameters.package }} ${{ parameters.version }}
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))
    inputs:
      azureSubscription: "JEG-Infrastructure"
      scriptType: "bash"
      workingDirectory: $(Pipeline.Workspace)
      scriptLocation: "inlineScript"
      inlineScript: |
        az artifacts universal download \
          --organization "${{ parameters.organization }}" \
          --feed "${{ parameters.feed }}" \
          --name "${{ parameters.package }}" \
          --version "${{ parameters.version }}" \
          --path "./tools/${{ parameters.package }}"
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

  - bash: |
      set -euo pipefail
      archive="$(find "./tools/${{ parameters.package }}" -maxdepth 1 -type f -name '*.tar.gz' -print -quit)"
      tar xf "$archive" -C "./tools/${{ parameters.package }}"
      rm "$archive"
      echo "##vso[task.prependpath]$(Pipeline.Workspace)/tools/${{ parameters.package }}"
    displayName: Extract ${{ parameters.package }}
    workingDirectory: $(Pipeline.Workspace)
    condition: and(succeeded(), eq(variables['hasExistingImages'], 'true'))