parameters:
  - name: image
    type: string
  - name: tag
    type: string

steps:
  - bash: |
      trivy image \
        --vuln-type os \
        --ignore-unfixed \
        --exit-code 1 \
        --format json \
        --scanners vuln \
        --output "./trivy-report.json" \
        "${{ parameters.image }}"
      
      TRIVY_STATUS=$?
      
      if [[ $TRIVY_STATUS -eq 0 ]]; then
        RUN_COPA="false"
      elif [[ $TRIVY_STATUS -eq 1 ]]; then
        RUN_COPA="true"
      else
        RUN_COPA="false"
        echo "##vso[task.logissue type=error]Trivy scan failed"
        exit 1
      fi
      echo "##vso[task.setvariable variable=RUN_COPA]$RUN_COPA"
    displayName: Scan image
    condition: and(succeeded(), ne('${{ parameters.image }}', ' '))
    workingDirectory: $(Pipeline.Workspace)

  - bash: |
      copa patch \
        --image ${{ parameters.image }} \
        --report ./trivy-report.json \
        --tag ${{ parameters.tag }} \
        --push
    displayName: Run copa
    condition: and(succeeded(), ne('${{ parameters.image }}', ' '), eq(variables['RUN_COPA'], 'true'))
    workingDirectory: $(Pipeline.Workspace)