name: CI

# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:    
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro: [cbld, mariner, ubuntu]
        version: [11]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build - Linux
        run: docker build -t mcr.microsoft.com/openjdk/jdk:${{ matrix.version }}-microsoft-${{ matrix.distro }} -f docker/${{ matrix.distro }}/Dockerfile.msopenjdk-${{ matrix.version }}-jdk .