ARG UBUNTU_VERSION="20.04"
ARG JAVA_VERSION="17"

FROM ubuntu:${UBUNTU_VERSION}

ARG UBUNTU_VERSION
ARG JAVA_VERSION

MAINTAINER Microsoft OpenJDK Support <openjdk-support@microsoft.com>
LABEL "Author"="Microsoft"
LABEL "Support"="Microsoft OpenJDK Support <openjdk-support@microsoft.com>"

RUN DEBIAN_FRONTEND=noninteractive
RUN     apt-get -qq update
RUN     apt-get -qq upgrade
RUN     apt-get -qq install --no-install-recommends tzdata ca-certificates fontconfig locales apt-transport-https wget binutils
RUN     echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
RUN     locale-gen en_US.UTF-8
RUN     wget -q https://packages.microsoft.com/config/ubuntu/${UBUNTU_VERSION}/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN     dpkg -i packages-microsoft-prod.deb
RUN     apt-get -qq update
RUN     apt-get -qq install msopenjdk-${JAVA_VERSION}
RUN     apt-get -qq purge apt-transport-https wget
RUN     apt-get -qq autoremove --purge
RUN     rm -rf /var/lib/apt/lists/*
RUN     echo java -Xshare:dump
RUN     java -Xshare:dump 

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

ENV JAVA_HOME=/usr/lib/jvm/msopenjdk-${JAVA_VERSION}-amd64
