ARG UBUNTU_VERSION="20.04"
ARG JAVA_VERSION="17"

FROM ubuntu:${UBUNTU_VERSION}

MAINTAINER Microsoft OpenJDK Support <openjdk-support@microsoft.com>
LABEL "Author"="Microsoft"
LABEL "Support"="Microsoft OpenJDK Support <openjdk-support@microsoft.com>"

ARG UBUNTU_VERSION
ARG JAVA_VERSION

ENV uv=${UBUNTU_VERSION:-"20.04"}
ENV jv=${JAVA_VERSION:-"17"}

RUN echo UBUNTU_VERSION=${UBUNTU_VERSION} > out && cat out
RUN echo JAVA_VERSION=${JAVA_VERSION} > out && cat out
RUN echo uv=${uv} > out && cat out
RUN echo jv=${jv} > out && cat out
RUN sh -c "echo ${JAVA_VERSION}" > out && cat out
RUN sh -c "echo ${UBUNTU_VERSION}" > out && cat out
