ARG IMAGE="mcr.microsoft.com/cbl-mariner/base/core"
ARG TAG="2.0"
FROM ${IMAGE}:${TAG}

LABEL "Author"="Microsoft"
LABEL "Support"="Microsoft OpenJDK Support <openjdk-support@microsoft.com>"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

ARG PKGS="temurin-8-jdk ca-certificates tzdata freetype"

# Install pre-reqs
RUN tdnf install -y ${PKGS} && \
    rm -rf /var/cache/tdnf

ENV JAVA_HOME=/usr/lib/jvm/temurin-8-jdk
