ARG IMGTOTEST=mcr.microsoft.com/openjdk/jdk:8-mariner

FROM mcr.microsoft.com/openjdk/jdk:8-mariner as builder
ADD NonRootUser.java /NonRootUser.java
RUN javac -source 1.8 -target 1.8 NonRootUser.java && jar cfe /app.jar NonRootUser NonRootUser.class

FROM ${IMGTOTEST} as runner
USER app
COPY --from=builder /app.jar /app.jar
CMD ["java", "-ea", "-jar", "/app.jar"]
