# DisableDockerDetector "Base image is obtained from internal registry"
FROM chisel-base

USER root

ENV JAVA_HOME=/usr/jdk
ENV PATH=$PATH:$JAVA_HOME/bin

COPY --from=mcr.microsoft.com/openjdk/jdk:21-ubuntu /usr/lib/jvm/msopenjdk-21-amd64 $JAVA_HOME

ENTRYPOINT [ "/usr/jdk/bin/java" ]
