#!/bin/bash
#
# Commits versions.json on a dedicated branch, force-pushes it, and opens a
# pull request on GitHub (or refreshes the existing open one). CI-agnostic:
# authentication is provided via the GH_AUTH_HEADER environment variable, which
# must contain a full HTTP Authorization header for github.com, e.g.:
#
#     AUTHORIZATION: basic <base64-token>
#
# The same credential is expected to authorize `git push` to origin (e.g. set as
# an http extraheader in git config by the caller).
#
# Usage:
#   GH_AUTH_HEADER="..." scripts/open-version-pr.sh <repo_slug> <base_branch> <bump_branch>
#
# Example:
#   scripts/open-version-pr.sh microsoft/openjdk-docker main auto/update-jdk-versions

set -euo pipefail

REPO_SLUG="${1:?repo slug required (e.g. microsoft/openjdk-docker)}"
BASE_BRANCH="${2:?base branch required (e.g. main)}"
BUMP_BRANCH="${3:?bump branch required (e.g. auto/update-jdk-versions)}"

if [[ -z "${GH_AUTH_HEADER:-}" ]]; then
  echo "error: GH_AUTH_HEADER environment variable is required" >&2
  exit 1
fi

owner="${REPO_SLUG%%/*}"
api="https://api.github.com/repos/${REPO_SLUG}"

# Reuse the same branch every run: -C resets it to the current commit so an
# existing (stale) branch is force-updated with the latest versions.
git switch -C "${BUMP_BRANCH}"
git add versions.json
git commit -m "Update JDK versions from upstream release sources"
git push -f origin "HEAD:refs/heads/${BUMP_BRANCH}"

# Check if there is already an open PR for this branch. If none is open, create
# one; if one exists, the force-push above already updated it.
open_count="$(curl -fsSL -H "${GH_AUTH_HEADER}" -H "Accept: application/vnd.github+json" \
  "${api}/pulls?state=open&head=${owner}:${BUMP_BRANCH}" | jq 'length')"

if [[ "${open_count}" != "0" ]]; then
  echo "An open PR already exists for ${BUMP_BRANCH}; updated it with a force-push."
  exit 0
fi

body="Automated update of versions.json from upstream release sources: the Microsoft Build of OpenJDK download page (msopenjdk) and the Adoptium API (temurin). Generated by the Update JDK Versions pipeline."
payload="$(jq -n \
  --arg title "Update JDK versions" \
  --arg head "${BUMP_BRANCH}" \
  --arg base "${BASE_BRANCH}" \
  --arg body "${body}" \
  '{title: $title, head: $head, base: $base, body: $body}')"

curl -fsSL -X POST -H "${GH_AUTH_HEADER}" -H "Accept: application/vnd.github+json" \
  "${api}/pulls" -d "${payload}" | jq -r '"Created PR: " + .html_url'
